### ISSUE TITLE
Connection always fails

### ISSUE THREAD

**Issue by AbeerBPi** [balenalabs/balena-cam#63]
https://forums.balena.io/t/balenacam-connection-always-fails-valueerror-does-not-appear-to-be-an-ipv4-or-ipv6-address/86504?u=abeerb

Appreciate all help!

**Comment by webtop** [comment]
Follow this PR instructions: https://github.com/balenalabs/balena-cam/pull/62

I had the same issue

**Comment by mbalamat** [comment]
@AbeerBPi assuming that the above solution helped you, I'll close this, if you have any issue feel free to re-open this issue.
