### ISSUE TITLE
libjasper-dev missing again

### ISSUE THREAD

**Issue by Esser420** [balenalabs/balena-cam#64]
I saw that this has been an issue before and that there was a fix at that time. Now builds from master are failing again due to the libjasper-dev package missing.

**Comment by mbalamat** [comment]
Hello @Esser420 I just tried to build it against a pi3 application and it works. Can you provide some more info about your setup?
Device type?
Camera module?
BalenaOS version?

**Comment by Esser420** [comment]
Ok I had a friend recently got the build working on an rpi0, I'll check if I didn't do any mistake.

**Comment by mbalamat** [comment]
@Esser420 you can paste here the output of the build. Especially the lines that say what base image was used, this might tell us something.

**Comment by mbalamat** [comment]
closing for now, if you encounter the issue feel free to re-open this,
