### ISSUE TITLE
Stable Rasberry Pi Zero W config?

### ISSUE THREAD

**Issue by sepulworld** [balenalabs/balena-cam#71]
Hi! Does anyone have a stable Raspberry Pi Zero W config they could share? I've tried a couple gpu memory settings... 128 and 256 but my camera will run for a minute or two and then lock up. Then the Balena supervisor restarts it I believe. I don't see much in the Balena logs for the device in the GUI, but Im assuming it is GPU memory related.  Any advice / documentation for Pi Zero would be appreciated!

**Comment by mbalamat** [comment]
@sepulworld can you try removing all the GPU mem vars and try different values for the `BALENA_HOST_CONFIG_gpu_mem` eg set it to 96? Also what balenaOS/supervisor version are you running? FYI we respond very quickly in our [forums](https://forums.balena.io/).
