### ISSUE TITLE
Show date and time in stream

### ISSUE THREAD

**Issue by leonpierre** [balenalabs/balena-cam#78]
Is this possible?

**Comment by mbalamat** [comment]
Hello @leonpierre yes it is. In general, balenaCam uses opencv to get the frame from the camera. So you can put whatever you want on a frame, you can even apply CV algorithms before returning it. WRT to your question, a user asked the same in our forums I can't find the forums post but I found the fork that this is implemented in, here is the diff that does this https://github.com/shams3049/balena-cam/commit/b0ca3845a4bb62f213f3e21c3cb43d3670315793.

**Comment by mbalamat** [comment]
Also, feel free to send us a PR with this addition, here. I am closing this, for now, feel free to re-open it if you have any issues.
